apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: iotSocketBridge.yaml
  name: iot-socket-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iot-socket-bridge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iot-socket-bridge
    spec:
      containers:
        - image: intel-server-03:5000/iotsocketbridge
          name: iot-socket-bridge
          ports:
            - containerPort: 8889
          imagePullPolicy: Always
          env:
            - name: KAFKA_TOPIC
              value: "insideSensors"
            - name: SOCKET_HOST
              value: "0.0.0.0"
            - name: SOCKET_PORT
              value: "8889"
          envFrom:
            - configMapRef:
                name: kafka-config
